name: pokeslots-stats

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy pandas plotnine
    - name: Run tests
      run: |
        make test
    - name: Run smoke tests
      run: |
        python pokeslots-stats/__main__.py pokemon_info data/pokemon.csv
        python pokeslots-stats/__main__.py simulate data/pokemon.csv data/dummy_probabilities.json --num_rolls 100 --num_cases 10 --autorelease
